import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../shared/styles/globals.css'
import QueryWrapper from '@/shared/lib/query-wrapper'
import ToasterWrapper from '@/shared/lib/toast-wrapper'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<QueryWrapper>
					<ToasterWrapper>{children}</ToasterWrapper>
				</QueryWrapper>
			</body>
		</html>
	)
}
